### RECUPERAR TODAS LAS ORDENES
GET http://localhost:5000/orders


### RECUPERAR UNA ORDEN POR SU ID
GET http://localhost:5000/orders/357a1f76-9ed5-4227-93d4-174f41c39872


### RECUPERAR LAS ORDENES POR USUARIO (ID)
GET http://localhost:5000/orders/user/b655b696-9008-4ecc-aac9-65a6bebeb54e

### CREAR UNA ORDEN
POST http://localhost:5000/orders
Content-Type: application/json

{
    "userId": "b655b696-9008-4ecc-aac9-65a6bebeb54e",
    "products": [
        {
            "productId": "0e543b36-5225-4011-bf71-7fed8f514c72",
            "quantity": 2
        }
    ]
}

### RECUPERAR LOS DETALLES DE LA ORDEN POR SU ID
GET http://localhost:5000/orders/products/123e4567-e89b-12d3-a456-426614174000
### ELIMINAR UNA ORDEN POR SU ID
DELETE http://localhost:5000/orders/607468d6-7c0a-4ef7-a41a-63c2674e70c1