### RECUPERAR TODOS LOS LENTES
GET http://localhost:5000/glasses

### RECUPERAR SOLO UN LENTE POR SU ID
GET http://localhost:5000/glasses/79af640b-a448-46db-a255-85b91c2336d2

### RECUPERAR LENTE POR EL QUERY DEL FILTRO, ESTE PUEDE SER POR CATEGORIA, GENERO, FORMA O COLOR
GET http://localhost:5000/glasses?filter=sol

### CREAR UN NUEVO PRODUCTO
POST http://localhost:5000/glasses
Content-Type: application/json

{
      "id": 121,
      "brand": "Oakley",
      "price": 200,
      "category": "sol",
      "genre": "mujer",
      "shape": "heart",
      "color": "rainbow",
      "image": "https://assets.theplace.com/image/upload/t_pdp_img_m,f_auto,q_auto/v1/ecom/assets/products/tcp/3038342/3038342_BQ.png",
      "description": "Lentes de sol Oakley",
      "quantity": 1,
      "stock": 10
    }

### ACTUALIZAR UN PRODUCTO
PUT http://localhost:5000/glasses/79af640b-a448-46db-a255-85b91c2336d2
Content-Type: application/json
      
      {
            "brand": "Versace",
            "description": "Sunglasses with a black frame and black lenses",
            "category": "sol",
            "genre": "mujer",
            "shape": "squared",
            "color": "black",
            "price": 60,
            "image": "https://assets.sunglasshut.com/is/image/LuxotticaRetail/8053672947397__STD__shad__qt.png?impolicy=SGH_bgtransparent&width=1000",
            "quantity": 1,
            "stock": 10
      }

### ELIMINAR UN PRODUCTO
DELETE http://localhost:5000/glasses/79af640b-a448-46db-a255-85b91c2336d2